name: Tests

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build the application
        run: yarn build
        env:
          VITE_GA_KEY: ${{ secrets.GA_KEY }}
          VITE_API_URL: ${{ vars.API_URL }}
          VITE_ENABLE_LIGHT_MODE: true
          VITE_GITHUB_URL: ${{ vars.AGITHUB_URL }}
          VITE_LOADING_TEXT: ${{ vars.LOADING_TEXT }}
          VITE_META_TITLE: ${{ vars.META_TITLE }}
          VITE_META_DESCRIPTION: ${{ vars.META_DESCRIPTION }}
          VITE_META_KEYWORDS: ${{ vars.META_KEYWORDS }}
          VITE_META_COPYRIGHT: ${{ vars.META_COPYRIGHT }}
          VITE_META_TYPE: ${{ vars.META_TYPE }}
          VITE_META_URL: ${{ vars.META_URL }}
          VITE_META_IMAGE: ${{ vars.META_IMAGE }}
          VITE_CHAT_URL: ${{ vars.CHAT_URL }}
          VITE_SUBPAGE_URL: ${{ vars.SUBPAGE_URL }}
          VITE_DRAWINGS_URL: ${{ vars.DRAWINGS_URL }}
          VITE_ENABLE_CHAT_BOT: ${{ vars.ENABLE_CHAT_BOT }}
          DISABLE_ESLINT_PLUGIN: true
      - name: Delete items from S3
        run: aws s3 rm s3://$AWS_BUCKET_NAME --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME_PROD }}
      - name: Upload items to S3
        run: aws s3 sync build/ s3://$AWS_BUCKET_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME_PROD }}
      - name: Clear cache of Cloudfront
        run: aws cloudfront create-invalidation --distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID --paths /
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_PROD }}          

