name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build the application
        run: yarn build
        env:
          VITE_API_URL: ${{ vars.API_URL }}
          VITE_ENABLE_LIGHT_MODE: true
          VITE_GITHUB_URL: ${{ vars.AGITHUB_URL }}
          VITE_LOADING_TEXT: ${{ vars.LOADING_TEXT }}
          VITE_META_TITLE: ${{ vars.META_TITLE }}
          VITE_META_DESCRIPTION: ${{ vars.META_DESCRIPTION }}
          VITE_META_KEYWORDS: ${{ vars.META_KEYWORDS }}
          VITE_META_COPYRIGHT: ${{ vars.META_COPYRIGHT }}
          VITE_META_TYPE: ${{ vars.META_TYPE }}
          VITE_META_URL: ${{ vars.META_URL }}
          VITE_META_IMAGE: ${{ vars.META_IMAGE }}
          VITE_CHAT_URL: ${{ vars.CHAT_URL }}
          VITE_SUBPAGE_URL: ${{ vars.SUBPAGE_URL }}
          DISABLE_ESLINT_PLUGIN: true
